export { default as AuthService } from './authService'
export { default as PermissionService } from './permissonService'
export { default as AdminService } from './adminService'
export { default as DashboardService } from './dashboardService'
export {default as TeacherService} from './teacherService'