export { default as Dashboard } from './Dashboard'
export { default as Admins } from './Admins'
export { default as LoadingPage } from './LoadingPage'
export { default as Teachers } from './Teachers'
export { default as Directions } from './Directions'